classDiagram

%% Models
    class FilterListItemModel{
        name: String
        group: String
        isSelected: bool
    }
    class QualityModel{
        name: String
        aliases: List~String~
        intervals: List~int~
        notation: List~String~
    }
    class ChordModel{
        name: String
        nameAlt: List~String~
        root: Note
        tones: List~Note~
    }
    class ChordListItemModel{
        chord: ChordModel
        isSelected: bool
    }
    class PlayStateModel{
        isPlaying: bool = false
        isFirstTickPlayed: bool = false
        isRepeat: bool = false
        isCountDown: bool = false
        isShowNoteOn: bool = false
        isPianoQuizOn: bool = false
        bpm: int = 120
        volume: int = 50
        timeSignature: int = 4
        currentTick: int = 0
        displayChordCount: int = 8
        reGenerateCount: int = 4
        currentChordIndex: int = 0
    }
    class PianoStateModel{
        pressedKeys: Set[int]
    }
    class PresetModel{
        id: String
        name: String
        type: PresetType
        path: String
        chordList: List[ChordModel]
        createdAt: DateTime
        updatedAt: DateTime
    }
    class PresetStateModel{
        presets,: List[PresetModel] = []
        isLoading,: bool = false
        folderPath,: List[String] = []
        error: String?
    }
    class GuideStateModel{
        showPlayScreenGuide: bool = true
        showQuizModeGuide: bool = false
    }
    

%% Providers
    class SelectedChordsProvider{
        exposes: List[ChordModel]
    }
    class RandomChordsProvider{
        exposes: List~String~
    }
    class FilteredChordsProvider{
        exposes: List~ChordListItemModel~
    }
    class FilterMapProvider{
        exposes: Map~String,List[FilterListItemModel]~
    }
    class PlayStateProvider{
        exposes: PlayStateModel
    }
    class QualityProvider{
        exposes: Future~List~QualityModel~~
    }
    class ChordListProvider{
        exposes: Future~List~ChordListItemModel~~
    }
    class DeviceIdProvider{
        exposes: FutureOr~String~
    }
    class PianoStateProvider{
        exposes: PianoStateModel
    }
    class PresetStateProvider{
        exposes: Future~PresetStateModel~
    }
    class GuideStateProvider{
        exposes: Future~GuideStateModel~
    }
    

%% Relationships
    ChordListItemModel *-- ChordModel
    SelectedChordsProvider ..> ChordModel
    FilteredChordsProvider ..> ChordListItemModel
    FilterMapProvider ..> FilterListItemModel
    PlayStateProvider ..> PlayStateModel
    QualityProvider ..> QualityModel
    ChordListProvider ..> ChordListItemModel
    PianoStateProvider ..> PianoStateModel
    PresetStateProvider ..> PresetStateModel
    PresetModel *-- ChordModel
    PresetStateModel *-- PresetModel
    GuideStateProvider ..> GuideStateModel